add the secure-storage sample plugin
AdobeDocs/uxp-photoshop-plugin-samples pull request #20
Opened 2021-03-02 14:16 UTC by luninor

Fixes #12

2021-03-02 15:13 UTC, luninor commented
@ashryanbeats please review.

2021-03-04 18:22 UTC, kerrishotts requested changes
Amazing work. I've left some comments for your review.

2021-03-04 18:22 UTC, kerrishotts commented on secure-storage-sample/index.html
> +  </sp-body>
Let's use an `sp-textfield` here.

```
<sp-textfield id="secure">
    <sp-label slot="label">Enter Secure Key</sp-label>
</sp-textfield>
```

2021-03-04 18:22 UTC, kerrishotts commented on secure-storage-sample/index.js
> +const app = window.require("photoshop").app;
`app` isn't used anywhere, let's remove.

2021-03-04 18:22 UTC, kerrishotts commented on secure-storage-sample/index.js
> +    document.getElementById("secure").value = ""
Nit: missing semicolon.

2021-03-04 18:22 UTC, kerrishotts commented on secure-storage-sample/index.js
> +}
Let's use `textContent` here instead of injecting HTML. Love the use of the template literal.

2021-03-04 18:22 UTC, kerrishotts commented on secure-storage-sample/index.js
> +  let string = "";
Let's add a comment that illustrates that secureStorage is returning a uInt8Array, and that 13-14 is building the string out of it.

2021-03-04 18:22 UTC, kerrishotts commented on secure-storage-sample/index.html
> +  }
I think this is unused; let's remove.

2021-03-04 18:22 UTC, kerrishotts commented on secure-storage-sample/index.html
> +    color: white;
We can remove this line; once we're using sp-% everywhere (see sp-textfield comment below), everything is theme aware by default.

2021-03-04 18:22 UTC, kerrishotts commented on secure-storage-sample/watch.sh
> +nodemon --exec "uxp plugin reload" -e js,jsx,html
Let's remove this file (no fault here, but we don't need to distribute this file.)

2021-03-04 18:22 UTC, kerrishotts commented on secure-storage-sample/index.html
> +  }
I think with the sp-textfield snippet that we won't need this bit of css.

2021-03-04 18:56 UTC, ashryanbeats requested changes
I left a few more minor comments. Great work!

2021-03-04 18:56 UTC, ashryanbeats commented on secure-storage-sample/index.js
> +    document.getElementById("secure").value = "";
Small ask, but can you make the indentation level consistent with the rest of the example?

2021-03-04 18:56 UTC, ashryanbeats commented on secure-storage-sample/README.md
> +This is a simple example plugin which demonstrates how we can store a value using the SecureStorage uxp API. No build steps are required to run the plugin.
"uxp" here should be all caps.

2021-03-05 20:28 UTC, ashryanbeats approved these changes
LGTM!

2021-03-05 20:32 UTC, kerrishotts approved these changes
LGTM :-) 

Again, excellent work!

2021-03-05 20:32 UTC, merged